
<div class="container">
	<div class="row">
		<div class="center-items-g">
			<h5 class="card-title">Usuário</h5>
			<form class="row g-3 formRegister mt-3">
				<div class="col-md-6">
					<input type="text" class="form-control" placeholder="CPF/CNPJ" id="cpf">
				</div>

				<div class="col-md-6">
					<input type="nome" class="form-control" placeholder="Nome Completo" id="nomecompleto">
				</div>

				<div class="col-md-6">
					<input type="email" class="form-control" placeholder="E-mail" id="email">
				</div>

				<div class="col-md-2">
					<input type="text" class="form-control" maxlength="2" size="2" placeholder="DDD (11)"
						   id="ddd_telefone"
						   name="id_telefone" required="required" pattern="[0-9]+$"/>
				</div>

				<div class="col-md-4">
					<input type="text" class="form-control" placeholder="Telefone 9999-9999" id="telefone"
						   name="telefone" required="required" pattern="[0-9]+$"/>
				</div>

				<div class="col-md-2">
					<input type="text" class="form-control" maxlength="2" size="2" placeholder="DDD (11)"
						   id="ddd_celular"
						   name="id_celular" required="required" pattern="[0-9]+$"/>
				</div>

				<div class="col-md-4">
					<input type="text" class="form-control" placeholder="Celular 99999-9999" id="celular"
						   name="celular" required="required" pattern="[0-9]+$"/>
				</div>
			</form>

			<div class="text-center">
				<button class="w-65 mt-3 btn btn-cadastro" id="btnNovoUsuario" type="button">
					<svg xmlns="http://www.w3.org/2000/svg" width="25" height="22" fill="currentColor"
						 class="bi bi-person-plus-fill" viewBox="0 0 16 16">
						<path d="M1 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H1zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"/>
						<path fill-rule="evenodd"
							  d="M13.5 5a.5.5 0 0 1 .5.5V7h1.5a.5.5 0 0 1 0 1H14v1.5a.5.5 0 0 1-1 0V8h-1.5a.5.5 0 0 1 0-1H13V5.5a.5.5 0 0 1 .5-.5z"/>
					</svg>
					Cadastrar usuário
				</button>
			</div>
		</div>
	</div>
</div>

