<main class="bg-blue center-main-empresa">
    <div class="container">
        <div class="row p-3">
            <div class="card-body">
                <form class="formCnpj" id="FormCadastro">
                    <div class="row mb-2">
                        <div class="col-md-6 mb-2">

                            <input type="text" class="form-control" placeholder="CPF/CNPJ" id="cpf" name="cpf"
                                   required="required" pattern="\d*"/>
                        </div>
                    </div>

                    <div class="row mb-2">
                        <div class="col-md-6 mb-2">
                            <input type="text" class="form-control " placeholder="Nome" id="nome" name="nome"
                            >
                        </div>

                        <div class="col-md-6 mb-2">
                            <input type="email" class="form-control" placeholder="E-mail" id="email" name="email">
                        </div>
                    </div>

                    <div class="row mb-2">
                        <div class="col-4 col-sm-3 col-md-2 col-lg-2 col-xl-2 mb-2">
                            <input type="text" class="form-control" maxlength="2" size="2" placeholder="DDD"
                                   id="ddd_telefone"
                                   name="ddd_telefone" pattern="\d*"/>
                        </div>

                        <div class="col-8 col-sm-9 col-md-4 col-lg-4 col-xl-4 mb-2">
                            <input type="text" class="form-control" placeholder="Telefone" id="telefone"
                                   name="telefone" pattern="\d*"/>
                        </div>

                        <div class="col-4 col-sm-3 col-md-2 col-lg-2 col-xl-2 mb-2">
                            <input type="text" class="form-control" placeholder="DDD"
                                   id="ddd_celular"
                                   name="ddd_celular" pattern="\d*"/>
                        </div>

                        <div class="col-8 col-sm-9 col-md-4 col-lg-4 col-xl-4 mb-2">
                            <input type="text" class="form-control" placeholder="Celular" id="celular"
                                   name="celular" pattern="\d*"/>
                        </div>
                    </div>

                    <div class="row mb-2 text-center">
                        <div class="mb-2">
                            <button type="button" id="btnNovoUsuario" class="btn btn-danger ">
                                <svg xmlns="http://www.w3.org/2000/svg" width="25" height="22" fill="currentColor"
                                     class="bi bi-person-plus-fill" viewBox="0 0 16 16">
                                    <path d="M1 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H1zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"/>
                                    <path fill-rule="evenodd"
                                          d="M13.5 5a.5.5 0 0 1 .5.5V7h1.5a.5.5 0 0 1 0 1H14v1.5a.5.5 0 0 1-1 0V8h-1.5a.5.5 0 0 1 0-1H13V5.5a.5.5 0 0 1 .5-.5z"/>
                                </svg>
                                Cadastrar
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</main>

